import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { contactInfo } from '@/config/contact';
export const Footer = () => {
    const instagramUrl = contactInfo.instagram;
    const youtubeUrl = contactInfo.youtube || 'https://youtube.com';
    const base = import.meta.env.BASE_URL || '/';
    return (_jsxs("footer", { className: "site-footer", children: [_jsxs("div", { className: "container site-footer__inner", children: [_jsx("div", { className: "site-footer__left", children: _jsxs("a", { className: "social-btn", href: instagramUrl, target: "_blank", rel: "noreferrer", "aria-label": "Abrir Instagram", children: [_jsx("span", { className: "social-btn__icon", "aria-hidden": true, children: _jsxs("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", xmlns: "http://www.w3.org/2000/svg", children: [_jsx("rect", { x: "3", y: "3", width: "18", height: "18", rx: "5", stroke: "#101E39", strokeWidth: "2" }), _jsx("circle", { cx: "12", cy: "12", r: "4.5", stroke: "#101E39", strokeWidth: "2" }), _jsx("circle", { cx: "17.5", cy: "6.5", r: "1.5", fill: "#101E39" })] }) }), _jsx("span", { className: "social-btn__label", children: "Instagram" })] }) }), _jsx("div", { className: "site-footer__logoWrap", "aria-label": "Marca", children: _jsx("img", { className: "site-footer__logo", src: `${base}loguito.png`, alt: "Figueroa Trainer", width: 160, height: 60, onError: (e) => { e.currentTarget.src = `${base}logo.png`; }, loading: "lazy" }) }), _jsx("div", { className: "site-footer__right", children: _jsxs("a", { className: "social-btn", href: youtubeUrl, target: "_blank", rel: "noreferrer", "aria-label": "Abrir YouTube", children: [_jsx("span", { className: "social-btn__icon", "aria-hidden": true, children: _jsxs("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", xmlns: "http://www.w3.org/2000/svg", children: [_jsx("rect", { x: "2.5", y: "6", width: "19", height: "12", rx: "3", stroke: "#101E39", strokeWidth: "2" }), _jsx("path", { d: "M10 9.5L15 12L10 14.5V9.5Z", fill: "#101E39" })] }) }), _jsx("span", { className: "social-btn__label", children: "YouTube" })] }) })] }), _jsxs("div", { className: "container", style: { textAlign: 'center', marginTop: '.75rem', opacity: .75, fontSize: '.85rem' }, children: ["\u00A9 ", new Date().getFullYear(), " Figueroa Trainer. Todos los derechos reservados."] })] }));
};
export default Footer;
